class Nature < ActiveHash::Base
  self.data = [
    {id: 11, name: "まじめ"},
    {id: 12, name: "さみしがり"},
    {id: 13, name: "いじっぱり"},
    {id: 14, name: "やんちゃ"},
    {id: 15, name: "ゆうかん"},
    {id: 21, name: "ずぶとい"},
    {id: 22, name: "きまぐれ"},
    {id: 23, name: "わんぱく"},
    {id: 24, name: "のうてんき"},
    {id: 25, name: "のんき"},
    {id: 31, name: "ひかえめ"},
    {id: 32, name: "おっとり"},
    {id: 33, name: "すなお"},
    {id: 34, name: "うっかりや"},
    {id: 35, name: "れいせい"},
    {id: 41, name: "おだやか"},
    {id: 42, name: "おとなしい"},
    {id: 43, name: "しんちょう"},
    {id: 44, name: "てれや"},
    {id: 45, name: "なまいき"},
    {id: 51, name: "おくびょう"},
    {id: 52, name: "せっかち"},
    {id: 53, name: "ようき"},
    {id: 54, name: "むじゃき"},
    {id: 55, name: "がんばりや"},
  ]
end
